'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
'''
# My soluton
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = sorted(s)
        t = sorted(t)
        
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        return t[-1]


# use count

class Solution:
    def findTheDifference(self, s: 'str', t: 'str') -> 'str':
        for i in t:
            if t.count(i)!=s.count(i):
                return i


# use string replace

class Solution:
    def findTheDifference(self, s: 'str', t: 'str') -> 'str':
        for letter in s:
            t = t.replace(letter,'',1)
            
        return t

# use XOR

class Solution(object):
    """
    xor
    """
    def findTheDifference(self, s, t):
        code = 0
        for ch in s + t:
            code ^= ord(ch)
        return chr(code)
